-- MySQL Script generated by MySQL Workbench
-- Thu Jun 27 14:22:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Consulta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Consulta` ;

CREATE TABLE IF NOT EXISTS `Consulta` (
  `ID` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Hora` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Dentista_ID` INT NOT NULL,
  `Recepicionista_ID` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Pagamento_ID` INT NOT NULL,
  `Pagamento_Valor` DECIMAL NOT NULL,
  `Tratamento_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Dentista_ID`, `Recepicionista_ID`, `Paciente_idPaciente`, `Pagamento_ID`, `Pagamento_Valor`, `Tratamento_ID`),
  CONSTRAINT `fk_Consulta_Dentista1`
    FOREIGN KEY (`Dentista_ID`)
    REFERENCES `Dentista` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Recepicionista1`
    FOREIGN KEY (`Recepicionista_ID`)
    REFERENCES `Recepicionista` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Pagamento1`
    FOREIGN KEY (`Pagamento_ID` , `Pagamento_Valor`)
    REFERENCES `Pagamento` (`ID` , `Valor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Tratamento1`
    FOREIGN KEY (`Tratamento_ID`)
    REFERENCES `Tratamento` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Consulta_Dentista1_idx` ON `Consulta` (`Dentista_ID` ASC) VISIBLE;

CREATE INDEX `fk_Consulta_Recepicionista1_idx` ON `Consulta` (`Recepicionista_ID` ASC) VISIBLE;

CREATE INDEX `fk_Consulta_Paciente1_idx` ON `Consulta` (`Paciente_idPaciente` ASC) VISIBLE;

CREATE INDEX `fk_Consulta_Pagamento1_idx` ON `Consulta` (`Pagamento_ID` ASC, `Pagamento_Valor` ASC) VISIBLE;

CREATE INDEX `fk_Consulta_Tratamento1_idx` ON `Consulta` (`Tratamento_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Dentista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dentista` ;

CREATE TABLE IF NOT EXISTS `Dentista` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(150) NOT NULL,
  `Telefone` VARCHAR(11) NULL,
  `CRO` VARCHAR(8) NOT NULL,
  `Especialidade` VARCHAR(50) NULL,
  `Email` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fornecedor` ;

CREATE TABLE IF NOT EXISTS `Fornecedor` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Endereço` VARCHAR(45) NULL,
  `Telefone` VARCHAR(11) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gasto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Gasto` ;

CREATE TABLE IF NOT EXISTS `Gasto` (
  `Material Odontológico_ID` INT NOT NULL,
  `Tratamento_ID` INT NOT NULL,
  PRIMARY KEY (`Material Odontológico_ID`, `Tratamento_ID`),
  CONSTRAINT `fk_Material Odontológico_has_Tratamento_Material Odontológi1`
    FOREIGN KEY (`Material Odontológico_ID`)
    REFERENCES `Material Odontológico` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Material Odontológico_has_Tratamento_Tratamento1`
    FOREIGN KEY (`Tratamento_ID`)
    REFERENCES `Tratamento` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Material Odontológico_has_Tratamento_Tratamento1_idx` ON `Gasto` (`Tratamento_ID` ASC) VISIBLE;

CREATE INDEX `fk_Material Odontológico_has_Tratamento_Material Odontoló_idx` ON `Gasto` (`Material Odontológico_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Material Odontológico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Material Odontológico` ;

CREATE TABLE IF NOT EXISTS `Material Odontológico` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Desrição` VARCHAR(70) NULL,
  `Quantidade` INT NOT NULL,
  `Fornecedor_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Fornecedor_ID`),
  CONSTRAINT `fk_Material Odontológico_Fornecedor1`
    FOREIGN KEY (`Fornecedor_ID`)
    REFERENCES `Fornecedor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Material Odontológico_Fornecedor1_idx` ON `Material Odontológico` (`Fornecedor_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Paciente` ;

CREATE TABLE IF NOT EXISTS `Paciente` (
  `idPaciente` INT NOT NULL,
  `Nome` VARCHAR(150) NOT NULL,
  `Data_Nasc` DATE NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(11) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idPaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pagamento` ;

CREATE TABLE IF NOT EXISTS `Pagamento` (
  `ID` INT NOT NULL,
  `Método` VARCHAR(50) NOT NULL,
  `Data` DATE NOT NULL,
  `Valor` DECIMAL NOT NULL,
  PRIMARY KEY (`ID`, `Valor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Recepicionista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recepicionista` ;

CREATE TABLE IF NOT EXISTS `Recepicionista` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(150) NOT NULL,
  `Telefone` VARCHAR(11) NULL,
  `Email` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tratamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tratamento` ;

CREATE TABLE IF NOT EXISTS `Tratamento` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(100) NULL,
  `Custo` DECIMAL NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
